apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: observability-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: asia-south1-docker.pkg.dev/project-61ebbdbd-73fb-43b8-93a/observability-repo/service-b:1.0
          ports:
            - containerPort: 8080
